### ISSUE TITLE
Create version tags

### ISSUE THREAD

**Issue by tknerr** [Zuehlke/cookbook-windev#3]
Maybe it's just a matter of `git push --tags`, but the metadata says we are on 0.2.0 but I don't see either the 0.1.0 or 0.2.0 tags in here.

**Comment by damphyr** [comment]
Been using stove to manage this together with the supermarket package. 
Not perfect but it does the job.

**Comment by tknerr** [comment]
:+1: tags are there, looks live stove creates them automagically

**Comment by tknerr** [comment]
@damphyr mind adding the stove call to the Rakefile? I always forget which args to pass...

**Comment by damphyr** [comment]
There are no arguments (--username and --key for the credentials to Chef supermarket, but we're not checking them in :wink:). It reads everything off the metadata and the git remote.

stove is a bit of a PITA because it sets the tag, then tries to login to GitHub and it never actually cleans up after itself so if something goes wrong you need to delete the tag locally and then possible remove the tag from GitHub etc. etc.

Not something I would put in the Rakefile like that.
